sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t temp_container -f Dockerfile.dev .

script:
  - docker run -e CI=true temp_container npm run test -- --coverage
