language: generic

services:
  - docker

before_install:
  - docker build -t temp_container -f Dockerfile.dev .

script:
  - docker run -e CI=true temp_container npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  app: $AWS_APP_NAME
  env: $AWS_ENV_NAME
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: $AWS_BUCKET_PATH
  on:
    branch: master
